name: Push Checkstyle report
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Grant permissions to gradle
        run: chmod +x gradlew
      - name: Run Checkstyle on Core
        run: ./gradlew :nolebotv2core:checkstyleMain
      - uses: jwgmeligmeyling/checkstyle-github-action@master
        with:
          path: 'nolebotv2core/build/reports/checkstyle/main.xml'
      - name: Run Checkstyle on WebApi
        run: ./gradlew :nolebotv2webapi:checkstyleMain
      - uses: jwgmeligmeyling/checkstyle-github-action@master
        with:
          path: 'nolebotv2core/build/reports/checkstyle/main.xml'
      - name: Run Checkstyle on shared
        run: ./gradlew :shared:checkstyleMain
      - uses: jwgmeligmeyling/checkstyle-github-action@master
        with:
          path: 'shared/build/reports/checkstyle/main.xml'