name: Push Checkstyle report
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Grant permissions to gradle
        run: chmod +x gradlew
      - name: Run PMD on Core
        run: ./gradlew :nolebotv2core:pmdMain
      - uses: jwgmeligmeyling/pmd-github-action@master
        with:
          path: 'nolebotv2core/build/reports/pmd/main.xml'
      - name: Run PMD on WebApi
        run: ./gradlew :nolebotv2webapi:pmdMain
      - uses: jwgmeligmeyling/pmd-github-action@master
        with:
          path: 'nolebotv2webapi/build/reports/pmd/main.xml'
      - name: Run PMD on shared
        run: ./gradlew :shared:pmdMain
      - uses: jwgmeligmeyling/pmd-github-action@master
        with:
          path: 'shared/build/reports/pmd/main.xml'